# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(606, 227)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.check1 = QtWidgets.QCheckBox(self.groupBox)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/py.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.check1.setIcon(icon)
        self.check1.setIconSize(QtCore.QSize(30, 30))
        self.check1.setObjectName("check1")
        self.check1.toggled.connect(self.OnCheck_Toggled)
        self.horizontalLayout.addWidget(self.check1)
        
        self.check2 = QtWidgets.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.check2.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/c.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.check2.setIcon(icon1)
        self.check2.setIconSize(QtCore.QSize(30, 30))
        self.check2.setObjectName("check2")
        self.check2.toggled.connect(self.OnCheck_Toggled)
        self.horizontalLayout.addWidget(self.check2)
        
        self.check3 = QtWidgets.QCheckBox(self.groupBox)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/cpp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.check3.setIcon(icon2)
        self.check3.setIconSize(QtCore.QSize(30, 30))
        self.check3.setObjectName("check3")
        self.check3.toggled.connect(self.OnCheck_Toggled)
        self.horizontalLayout.addWidget(self.check3)
        
        self.check4 = QtWidgets.QCheckBox(self.groupBox)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/cs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.check4.setIcon(icon3)
        self.check4.setIconSize(QtCore.QSize(30, 30))
        self.check4.setObjectName("check4")
        self.check4.toggled.connect(self.OnCheck_Toggled)
        self.horizontalLayout.addWidget(self.check4)
        
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.check1, self.check2)
        Dialog.setTabOrder(self.check2, self.check3)
        Dialog.setTabOrder(self.check3, self.check4)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "what is your favorite language?"))
        self.check1.setText(_translate("Dialog", "python"))
        self.check2.setText(_translate("Dialog", "c"))
        self.check3.setText(_translate("Dialog", "c++"))
        self.check4.setText(_translate("Dialog", "csharp"))
        self.label.setText(_translate("Dialog", "Hello"))

    def OnCheck_Toggled(self):
        if self.check1.isChecked():
            self.label.setText("You have select : "+ self.check1.text())
            
        if self.check2.isChecked():
            self.label.setText("You have select : "+ self.check2.text())
        
        if self.check3.isChecked():
            self.label.setText("You have select : "+ self.check3.text())
        
        if self.check4.isChecked():
            self.label.setText("You have select : "+ self.check4.text())
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
